# Build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

COPY . ./
RUN dotnet restore RecruiterAid_Api/RecruiterAid_Api.csproj
RUN dotnet publish RecruiterAid_Api/RecruiterAid_Api.csproj -c Release -o out

# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/out .

ENTRYPOINT ["dotnet", "RecruiterAid_Api.dll"]